projectID: "custom-dc-test"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://custom-dc-test-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
bucket: "custom-dc-test-resources"
gcfSA: "website-robot@custom-dc-test.iam.gserviceaccount.com"