projectID: "datcom-website-dev"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
bucket: "datcom-website-dev-resources"
tempLocation: "gs://datcom-store-dev-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
gcfSA: "website-robot@datcom-website-dev.iam.gserviceaccount.com"