projectID: "datcom-store"
instance: "prophet-branch-cache"
cluster: "prophet-branch-cache-c1"
dataflowTemplate: "gs://datcom-templates/templates/csv_to_bt_0.0.3"
dataPath: "gs://datcom-store"
controlPath: "gs://datcom-control/branch"
appProfileID: "batch"
